### ISSUE TITLE
Implement Academic Details form.

### ISSUE THREAD

**Issue by asimbera** [TeamOpencampus/opencampus#17]
Create a `Academic Details` form in `/src/pages/dashboard/SettingsPage.tsx`, inside `AcademicDetailsForm` component.

Following fields have to be added:

- type - Type of Course (Select)
- institute - Colage / Institute Name (Input)
- board - Board / Council / University (Input)
- stream - Department / Stream (Input)
- start_date - Start Date (Input) `DD-MM-YYYY`
- end_date - End Date (Input) `DD-MM-YYYY`
- marks - GPA / Percentage

Effected File: `/src/pages/dashboard/SettingsPage.tsx`
Scope: `AcademicDetailsForm`

Start after #13 is merged.

Assignees: @thatsuman 
Labels:

**Comment by thatsuman** [comment]
I'll do it
