### ISSUE TITLE
Implement Additional Documents form.

### ISSUE THREAD

**Issue by asimbera** [TeamOpencampus/opencampus#18]
Create `Additional Documents` form in `/src/pages/dashboard/SettingsPage.tsx`, inside `AdditionalDocumentsForm` component.

Following fields have to be included:
* photo - Photo (File)
* signature - Signature (File)
* identity_proof - Identity Proof (File)
* caste_certificate - Caste Certificate (File)

File type can be jpg/png/pdf. Max size can be 4MB.
May use file handling library like [use-file-picker](https://yarnpkg.com/package/use-file-picker).

Effected file: `/src/pages/dashboard/SettingsPage.tsx`
Scope: `AdditionalDocumentsForm`

**Comment by DepanSaha** [comment]
Let me do this....
