### ISSUE TITLE
Create Work Experience form.

### ISSUE THREAD

**Issue by asimbera** [TeamOpencampus/opencampus#25]
Create Work Experience form in `/src/pages/dashboard/SettingsPage.tsx` within `WorkExperienceForm` component.

Add the following fields in the form -
- have_exp - Do you have prior work experience? (CheckBox) 
- company - Pervious Company (Input)
- start_date_exp - Start date (Input)
- end_date_exp - End date (Input)
- last_salary - Last Salary (Input)

Effected file: `/src/pages/dashboard/SettingsPage.tsx`
Scope: `WorkExperienceForm`

> Follow the layout of `BasicDetailsForm`.

**Comment by priyanshumaitra** [comment]
Hello there, can you assign me to this issue?

**Comment by asimbera** [comment]
@priyanshumaitra বদ্দা কাজ কতদূর?

**Comment by priyanshumaitra** [comment]
> @priyanshumaitra বদ্দা কাজ কতদূর?

Complete. I'll push the changes tomorrow.

**Comment by priyanshumaitra** [comment]
Issue is fixed. The PR is #39
