### ISSUE TITLE
Create `Posts` creation modal

### ISSUE THREAD

**Issue by asimbera** [TeamOpencampus/opencampus#50]
Copy layout from `Students` page.
Then implement a `Post` creation form inside the modal.

Add the following fields:
- Company (Select)
- Job Title (Input)
- Location (Input)
- Salary (Input)
- Department (CheckboxGroup)
- Job Description (Textarea)

**Comment by DepanSaha** [comment]
Arigato Gosaimash

**Comment by thatsuman** [comment]
> Arigato Gosaimash

![image](https://user-images.githubusercontent.com/56498881/173145183-e3191b3d-e603-4054-971c-65a1d874aa30.png)
