### ISSUE TITLE
Validate `Add Company` in CompaniesPage

### ISSUE THREAD

**Issue by thatsuman** [TeamOpencampus/opencampus#51]
Add form validation functionality to `Add Company` modal in Companies Page

Effected file: `./src/pages/dashboard/college/CompaniesPage.tsx`

N.B Don't work on this until #49 is resolved

**Comment by asimbera** [comment]
Kaj suru koro bodda.

**Comment by thatsuman** [comment]
> Kaj suru koro bodda.

#52 merge er por modal e oi only 4te field er e validation check korte hobe toh?

**Comment by asimbera** [comment]
> #52 merge er por modal e oi only 3te field er e validation check korte hobe toh?

Hu, thik e dhorecho
